import { DM_Sans, Barlow, Alexandria } from "next/font/google";
import Header from "@/components/home/Header";
import Topbar from "@/components/home/Topbar";
import { useEffect, useState } from "react";
import Footer from "@/components/home/Footer";
import "@/styles/globals.css";


export const metadata = {
  title: "BBES",
  description: "Generated by create bbes app",
};

export default function App({ Component, pageProps }) {
  const [headerActive, setHeaderActive] = useState(false);
  useEffect(() => {
    const handleScroll = () => {
      setHeaderActive(window.scrollY > 200);
    };
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.addEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <div
      className="antialiased"
    >
      <Topbar />
      {/* static header */}
      <div className="relative z-10">
        <Header />
      </div>
      {/* animated header */}
      <div
        className={`w-full transition-transform duration-500 fixed top-0 left-0 z-50 ${
          headerActive ? "translate-y-0" : "-translate-y-full"
        }`}
      >
        <Header />
      </div>
      <Component {...pageProps} />
      <Footer />
    </div>
  );
}
